version: "3.9"

networks:
  default:
    name: npm_default
    external: true

services:
  rstudio:
    image: "chainguard/rstudio:latest"
    container_name: "actin"
    ports:
      - "8782:8787"
    volumes:
      - ./config:/home/rstudio/.config/rstudio
      - ./rstudio:/home/rstudio
      - ./Renviron:/home/rstudio/.Renviron
    environment:
      - USERNAME=username #these dont seem to do anything
      - PASSWORD=password
