---
# create a .env file with DB_PASSWORD and DB_ROOT_PASSWORD. when assigning domains to docker container names, pay attention to the below names

networks:
  default:
    name: npm_default
    external: true

services:
  shlink:
    image: shlinkio/shlink:stable
    restart: always
    container_name: shlink-server-backend
    environment:
      - GEOLITE_LICENSE_KEY=''
      - IS_HTTPS_ENABLED=false
      - DB_DRIVER=maria
      - DB_USER=shlink
      - DB_NAME=shlink
      - DB_PASSWORD='${DB_PASSWORD}'
      - DB_HOST=database
    depends_on:
      - database
    ports:
      - 8093:8080

  database:
    image: mariadb:10.11
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD='${DB_ROOT_PASSWORD}'
      - MARIADB_DATABASE=shlink
      - MARIADB_USER=shlink
      - MARIADB_PASSWORD='${DB_PASSWORD}'
    volumes:
      - ./mysql:/var/lib/mysql

  shlink-web-client:
    image: shlinkio/shlink-web-client
    restart: always
    container_name: shlink-gui-frontend
    depends_on:
      - shlink
    ports:
      - 8334:8080
